# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qchord.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(77, 180, 831, 311))
        self.label.setStyleSheet("background-image:url(:/Prefix1/board.png);\n"
"background-repeat:no-repeat;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 90, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.key_1 = QtWidgets.QLabel(self.centralwidget)
        self.key_1.setGeometry(QtCore.QRect(90, 420, 41, 41))
        self.key_1.setText("")
        self.key_1.setObjectName("key_1")
        self.key_2 = QtWidgets.QLabel(self.centralwidget)
        self.key_2.setGeometry(QtCore.QRect(120, 340, 31, 31))
        self.key_2.setText("")
        self.key_2.setObjectName("key_2")
        self.key_3 = QtWidgets.QLabel(self.centralwidget)
        self.key_3.setGeometry(QtCore.QRect(150, 420, 41, 41))
        self.key_3.setText("")
        self.key_3.setObjectName("key_3")
        self.key_4 = QtWidgets.QLabel(self.centralwidget)
        self.key_4.setGeometry(QtCore.QRect(183, 340, 31, 31))
        self.key_4.setText("")
        self.key_4.setObjectName("key_4")
        self.key_5 = QtWidgets.QLabel(self.centralwidget)
        self.key_5.setGeometry(QtCore.QRect(208, 420, 41, 41))
        self.key_5.setText("")
        self.key_5.setObjectName("key_5")
        self.key_10 = QtWidgets.QLabel(self.centralwidget)
        self.key_10.setGeometry(QtCore.QRect(383, 420, 41, 41))
        self.key_10.setText("")
        self.key_10.setObjectName("key_10")
        self.key_8 = QtWidgets.QLabel(self.centralwidget)
        self.key_8.setGeometry(QtCore.QRect(325, 420, 41, 41))
        self.key_8.setText("")
        self.key_8.setObjectName("key_8")
        self.key_6 = QtWidgets.QLabel(self.centralwidget)
        self.key_6.setGeometry(QtCore.QRect(266, 420, 41, 41))
        self.key_6.setText("")
        self.key_6.setObjectName("key_6")
        self.key_9 = QtWidgets.QLabel(self.centralwidget)
        self.key_9.setGeometry(QtCore.QRect(357, 340, 31, 31))
        self.key_9.setText("")
        self.key_9.setObjectName("key_9")
        self.key_7 = QtWidgets.QLabel(self.centralwidget)
        self.key_7.setGeometry(QtCore.QRect(295, 340, 31, 31))
        self.key_7.setText("")
        self.key_7.setObjectName("key_7")
        self.key_12 = QtWidgets.QLabel(self.centralwidget)
        self.key_12.setGeometry(QtCore.QRect(442, 420, 41, 41))
        self.key_12.setText("")
        self.key_12.setObjectName("key_12")
        self.key_11 = QtWidgets.QLabel(self.centralwidget)
        self.key_11.setGeometry(QtCore.QRect(418, 340, 31, 31))
        self.key_11.setText("")
        self.key_11.setObjectName("key_11")
        self.key_20 = QtWidgets.QLabel(self.centralwidget)
        self.key_20.setGeometry(QtCore.QRect(735, 420, 41, 41))
        self.key_20.setText("")
        self.key_20.setObjectName("key_20")
        self.key_15 = QtWidgets.QLabel(self.centralwidget)
        self.key_15.setGeometry(QtCore.QRect(560, 420, 41, 41))
        self.key_15.setText("")
        self.key_15.setObjectName("key_15")
        self.key_24 = QtWidgets.QLabel(self.centralwidget)
        self.key_24.setGeometry(QtCore.QRect(852, 420, 41, 41))
        self.key_24.setText("")
        self.key_24.setObjectName("key_24")
        self.key_19 = QtWidgets.QLabel(self.centralwidget)
        self.key_19.setGeometry(QtCore.QRect(705, 340, 31, 31))
        self.key_19.setText("")
        self.key_19.setObjectName("key_19")
        self.key_21 = QtWidgets.QLabel(self.centralwidget)
        self.key_21.setGeometry(QtCore.QRect(767, 340, 31, 31))
        self.key_21.setText("")
        self.key_21.setObjectName("key_21")
        self.key_13 = QtWidgets.QLabel(self.centralwidget)
        self.key_13.setGeometry(QtCore.QRect(500, 420, 41, 41))
        self.key_13.setText("")
        self.key_13.setObjectName("key_13")
        self.key_18 = QtWidgets.QLabel(self.centralwidget)
        self.key_18.setGeometry(QtCore.QRect(676, 420, 41, 41))
        self.key_18.setText("")
        self.key_18.setObjectName("key_18")
        self.key_23 = QtWidgets.QLabel(self.centralwidget)
        self.key_23.setGeometry(QtCore.QRect(828, 340, 31, 31))
        self.key_23.setText("")
        self.key_23.setObjectName("key_23")
        self.key_16 = QtWidgets.QLabel(self.centralwidget)
        self.key_16.setGeometry(QtCore.QRect(593, 340, 31, 31))
        self.key_16.setText("")
        self.key_16.setObjectName("key_16")
        self.key_17 = QtWidgets.QLabel(self.centralwidget)
        self.key_17.setGeometry(QtCore.QRect(618, 420, 41, 41))
        self.key_17.setText("")
        self.key_17.setObjectName("key_17")
        self.key_22 = QtWidgets.QLabel(self.centralwidget)
        self.key_22.setGeometry(QtCore.QRect(793, 420, 41, 41))
        self.key_22.setText("")
        self.key_22.setObjectName("key_22")
        self.key_14 = QtWidgets.QLabel(self.centralwidget)
        self.key_14.setGeometry(QtCore.QRect(530, 340, 31, 31))
        self.key_14.setText("")
        self.key_14.setObjectName("key_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "请输入和弦名称："))
        self.pushButton.setText(_translate("MainWindow", "查询"))
import src_rc
